Release/2.0.1 (#145)
* Fix bug where post type was not updated when updating posts db (#106)

* Update post type when posts are updated

* Parser modifications (#112)

* Added endpoint api/class/parse to trigger a update of all posts in a course manually.

* Updated parser to remove posts made private

The parser now keeps of all posts that are currently on
piazza and has a status other than 'deleted' or 'private'.
It then checks if any of the posts in the databse is not
included in the colletion of posts currently on piazza.
If so, that post is deleted from the database.

This is done in order to make sure that posts that were
once public but have been changed to private are removed
from the database.

Unfortunately it's not enough to check if the posts have
status 'private', as some private posts aren't returned
when fetching posts from piazza, while others are.

* Click Based Statistics (#109)

* Changes to:

1) Number of posts prevented. Now, denominator has only posts made
   by parqr users
2) Click based statistics

* Changes to:

1) Number of posts prevented. Now, denominator has only posts made
   by parqr users
2) Click based statistics

* Cleaner code returning only One parameter.

* Addition of weekly statistics function.

* Review Comments are being addressed in this particular append of the
commit.

* Minor refactoring in parser. (#114)

* Instructor Recs (#113)

* Added endpoint to send back past class recs

* .

* .

* allows cross origin requests to be made

* update

* Update string_utils.py

* remove nltk and update pytest version (#117)

* remove nltk and update pytest version

* update req

* Instructor answers (#118)

* Added endpoint to send back past class recs

* .

* .

* allows cross origin requests to be made

* update

* Added related course to Test course

* Added dynamic data field in event data

* Bryan (#119)

* added some docstrings

* got a basic schema for api

* porting to py3 and doing flask-restful

* temp commit!

* turned original app into python3

* not there yet

* deleted draft version of py3 restful

* added feedback functions in python3 from niklas

* using spacy for string-utils.py

* removed xrange from parser.py

* 1. NLTK import error: for Python3, download Pytest >=5.2.0
2. Replaced clean_and_split with spacy_clean

* Tested 3 API endpoints: Enroll User, Auth, Register Course
Common issues: json_schema_validate, PyJWT

* added Chirag's removing NLTK in modeltrain.py

* updated requirements

* fixed requirements

* fixed decorator s.t. verify non empty json request works

* jwt_required works. gotta use PARQR environment

* resolved comments from PR

* donwloading spacy en model in docker (that's weird)

* incorporated Chirag's nit

* update (#121)

* update

* update

* update

* fix some tests

* Refactoring into Flask-Restful (#120)

* added some docstrings

* got a basic schema for api

* porting to py3 and doing flask-restful

* temp commit!

* turned original app into python3

* not there yet

* refactoring branch created

* refactored into restful. still gotta tidy up things in app.py

* finished adding resources. next: testing

* fixed import errors. next: test out docker

* shit works!

* minor edits

* added feedback functions in refactored python3 from niklas

* added feedback functions in api.py

* adding all resources

* using spacy for better-text parsing

* deleting spacytest.py

* fixed docstring to say lemmatization

* debugged to get API endpoints working.
todo1: use marshmellow instead of json schema validator
todo2: figure out JWT situation

* incorporated comments from PR for branch 'bryan'

* 2 decorators still don't work.

* incorporated Chirag's PR comments except 2

* updated tests suite

* suggesting using marshmallow for json validating

* remove superflous schemas

* remove extra spaces at the end of line

* Minor changes from refactoring (#122)

* added some docstrings

* got a basic schema for api

* porting to py3 and doing flask-restful

* turned original app into python3

* finished adding resources. next: testing

* fixed import errors. next: test out docker

* added feedback functions in refactored python3 from niklas

* added feedback functions in api.py

* adding all resources

* using spacy for better-text parsing

* fixed docstring to say lemmatization

* debugged to get API endpoints working.
todo1: use marshmellow instead of json schema validator
todo2: figure out JWT situation

* incorporated comments from PR for branch 'bryan'

* 2 decorators still don't work.

* incorporated Chirag's PR comments except 2

* updated tests suite

* suggesting using marshmallow for json validating

* remove superflous schemas

* remove extra spaces at the end of line

* fixed some typos and changed api endpoint for courses enrolled

* changed logger format for Events

* ran thru Postman and check all API. Major bug: removing Posts field from Course seems to break 5 API endpoints

* changed the API endpoint for course usage stat

* made resources plural and minor changes

* Courses API refactoring done to match the new API doc

* All API refactoring except Feedback done to match the new API doc

* refactoring

* fix more syntax and add rec arg parsing

* only pull modified posts

* update circleci

* update tests

* update circleci

* remove unnecessary code

Co-authored-by: Chirag Tailor <tailorck@users.noreply.github.com>

* AWS Migration (#127)

* added some docstrings

* got a basic schema for api

* porting to py3 and doing flask-restful

* temp commit!

* turned original app into python3

* not there yet

* refactoring branch created

* refactored into restful. still gotta tidy up things in app.py

* finished adding resources. next: testing

* fixed import errors. next: test out docker

* shit works!

* minor edits

* added feedback functions in refactored python3 from niklas

* added feedback functions in api.py

* adding all resources

* using spacy for better-text parsing

* deleting spacytest.py

* fixed docstring to say lemmatization

* debugged to get API endpoints working.
todo1: use marshmellow instead of json schema validator
todo2: figure out JWT situation

* incorporated comments from PR for branch 'bryan'

* 2 decorators still don't work.

* incorporated Chirag's PR comments except 2

* updated tests suite

* suggesting using marshmallow for json validating

* remove superflous schemas

* remove extra spaces at the end of line

* fixed some typos and changed api endpoint for courses enrolled

* changed logger format for Events

* ran thru Postman and check all API. Major bug: removing Posts field from Course seems to break 5 API endpoints

* changed the API endpoint for course usage stat

* Add AWS Lambdas and change database to DDB calls

* Add Lambda alias to Parqr-Cleaner Lambda

* Fix imports for packaging

* Fix imports for packaging

* Flatten utils package

* Add courses endpoint

* Add courses endpoint

* Make parser only add new posts to DDB

* Change database to single DDB Posts

* Add logic to purge deleted posts

* Add logic to remove posts that were deleted

* Add Top_Post api call

* Add Course_Enrolled call

* Refactor endpoints

* move things to make merge easier

* Refactor files

* Add Feedback for AWS

* Add Recommendations and Event API calls

* Name CloudWatch Events and Disable Feedbacks in Query

* Fixes for AWS migration

* Add Lambda for Continuous Deployment

* Edit Create App Path and Separate from Init

* Move boto3 to function calls

* Move boto3 to function calls

* Add tests for AWS

* Comment out work for future

* Fix AWSGI line in requirements

* Fix function pointer

* Remove call to AWS in test and fix Flask error

* Make get courses faster

* Add direct resource path to parqr lambda

* added aws secret management

* Fix requested changes

* Change updater lambda to include a beta

* Add feedbacks call to parqr_lambda

* SyntaxError

* more changes

* add API endpoints for stage variables

* Add CORS

* Remove toxic line

* rever model_cache changes

* add uuid for event

* update model cache

* fix hello world. very important

* Add tests

* Fix import error

* pluralize courses for consistency

* Add message for activating a course

* Fix bugs

* Fix test

* Fix test bug

* Change already registered return value

* update event and courses endpoint

* update course api

* made some fixes on feedback lambda

* duplicate argument

* too many arguments in this one

* Add Variables for Lan

* Fix Decimal Bug

* ok im done

* Chirag made a mistakkkke

* Change API responses to match Swagger

Co-authored-by: Bryan Baek <baek@gatech.edu>
Co-authored-by: Bryan Baek <seungkwan.baek@gmail.com>
Co-authored-by: tailorck <cktailor34@gmail.com>

* Add pagination to DDB for recommendation

* Paginateddb (#143)

* Fix bug where post type was not updated when updating posts db (#106) (#107)

* Update post type when posts are updated

* Fix syntax, style errors

* Add pagination to DDB for recommendation

Co-authored-by: Noah Bilgrien <nobillygreen@gmail.com>
Co-authored-by: Chirag Tailor <tailorck@users.noreply.github.com>

* Paginateddb (#144)

* Add pagination to DDB for recommendation

* Fix for student too

Co-authored-by: Noah Bilgrien <nobillygreen@gmail.com>
Co-authored-by: Chirag Tailor <tailorck@users.noreply.github.com>

Co-authored-by: Roy Finkelberg <roy.finkelberg@gmail.com>
Co-authored-by: Niklas Gustafsson <niklas.erik.gustafson@gmail.com>
Co-authored-by: Kachakhiladi <35397921+Kachakhiladi@users.noreply.github.com>
Co-authored-by: Chirag Tailor <tailorck@users.noreply.github.com>
Co-authored-by: Bryan Baek <seungkwan.baek@gmail.com>
Co-authored-by: Bryan Baek <baek@gatech.edu>
Co-authored-by: tailorck <cktailor34@gmail.com>
Co-authored-by: Noah Bilgrien <nobillygreen@gmail.com>